using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DG.Tweening;

public class elevator : MonoBehaviour
{
    public float movedistance = 2.0f;
    public float moveDuration = 2.0f; // ˆÚ“®‚É‚©‚©‚éŠÔ

    public bool UpTrigger = false;
    public bool DownTrigger = false;

    private bool isMovingUp = true; // Œ»İã¸’†‚©‚Ç‚¤‚©
    public float interval = 2.0f; // ã¸‚Æ‰º~‚ÌØ‚è‘Ö‚¦ŠÔŠÔŠu

    public bool isPaused = false;

    void Start()
    {
        // interval•b‚²‚Æ‚ÉChangeDirectionƒƒ\ƒbƒh‚ğŒJ‚è•Ô‚µŒÄ‚Ño‚·
        InvokeRepeating("ChangeDirection", interval, interval);
    }

    void ChangeDirection()
    {
        if (!isPaused)
        {
            isMovingUp = !isMovingUp;
            if (isMovingUp)
            {
                UpTrigger = true;
            }
            if (!isMovingUp)
            {
                DownTrigger = true;
            }
        }
    }

    void Update()
    {
        if (UpTrigger)
        {
            UpUpdate();
        }
        if (DownTrigger)
        {
            DownUpdate();
        }
    }

    public void UpUpdate()
    {
        transform.DOMoveY(transform.position.y + movedistance, moveDuration);
        UpTrigger = false;
    }

    public void DownUpdate()
    {
        transform.DOMoveY(transform.position.y - movedistance, moveDuration);
        DownTrigger = false;
    }
}
